#!/usr/bin/env bash
# Ensure Nginx runs as 'nginx' user and listens on port 8080
sudo pkill apache2
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo service nginx restart
